apps-$(CONFIG_APP_<APP_NAME>) += <app_name>

# list of libraries the app needs to build
<app_name>-y = common libsel4 libmuslc libcpio libsel4utils libsel4muslcsys libsel4allocman libsel4test libelf libplatsupport libsel4platsupport libsel4vspace
<app_name>: kernel_elf $(<app_name>-y)

